name: Publish Docker
on: 
  push:
    paths-ignore:
    - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gitlab-time-back
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: docker/build-push-action@v2
      with:
        username: scdcompany
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: scdcompany/gitlab-time-back
        tags: latest